name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # Change this if you're not using Node.js

      - name: Run Tests
        run: npm test  # Change this to your test command
